# Generated by Django 5.1.7 on 2025-05-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entity_integrationlog_fielddefinition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fielddefinition',
            old_name='field_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=50),
        ),
    ]
